# Generated by Django 4.2.7 on 2023-11-26 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(blank=True, choices=[('STORE', '입고'), ('RELEASE', '출고')], max_length=40, verbose_name='구분')),
                ('unit_price', models.BigIntegerField(verbose_name='단가')),
                ('quantity', models.BigIntegerField(verbose_name='수량')),
                ('total_price', models.BigIntegerField(verbose_name='총 금액')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='마지막으로 수정된 날짜')),
            ],
            options={
                'verbose_name': '재고',
                'verbose_name_plural': '재고',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='품목명')),
                ('store', models.BigIntegerField(default=0, verbose_name='입고')),
                ('release', models.BigIntegerField(default=0, verbose_name='출고')),
                ('total_count', models.BigIntegerField(default=0, verbose_name='총 갯수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='마지막으로 수정된 날짜')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='관리자')),
            ],
            options={
                'verbose_name': '품목',
                'verbose_name_plural': '품목',
            },
        ),
        migrations.CreateModel(
            name='InventoryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(blank=True, choices=[('STORE', '입고'), ('RELEASE', '출고')], max_length=40, verbose_name='구분')),
                ('unit_price', models.BigIntegerField(verbose_name='단가')),
                ('quantity', models.BigIntegerField(verbose_name='수량')),
                ('total_price', models.BigIntegerField(verbose_name='총 금액')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('inventory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventory', verbose_name='재고')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.item', verbose_name='품목')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='관리자')),
            ],
            options={
                'verbose_name': '재고 관리 이력',
                'verbose_name_plural': '재고 관리 이력',
            },
        ),
        migrations.AddField(
            model_name='inventory',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.item', verbose_name='품목'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='관리자'),
        ),
    ]
